### ISSUE TITLE
gettting warning when installing node.js

### ISSUE THREAD

**Issue by RIBTAS007** [Girlscript-Deheradun/Web-Development#6]
Please see the comment below, and help me to resolve it.

**Comment by RIBTAS007** [comment]
C:\Users\Win8.1>npm install express
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Win8.1\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Win8.1\package.json'
npm WARN Win8.1 No description
npm WARN Win8.1 No repository field.
npm WARN Win8.1 No README data
npm WARN Win8.1 No license field.

**Comment by hitiksaini** [comment]
You don't have package.json in your current directory - use npm init Also, it is possible that you are in the wrong directory - cd to the folder where your package.json is located and then try again.

**Comment by hitiksaini** [comment]
Have you followed each step of node installation? stated in the Repository
run this command -> node --version  it shows you the version?or not?

**Comment by RIBTAS007** [comment]
Yes , After installing node js and doing Nodejs -- version successfully , i used npm install -g express and from that time I am getting this error, here's the output.

C:\Users\Win8.1>npm install -g express
+ express@4.17.1
added 50 packages from 37 contributors in 16.093s

C:\Users\Win8.1>npm install express --save
npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\Win8.1\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Win8.1\package.json'
npm WARN Win8.1 No description
npm WARN Win8.1 No repository field.
npm WARN Win8.1 No README data
npm WARN Win8.1 No license field.

**Comment by RIBTAS007** [comment]
C:\Users\Win8.1>node --version
v12.18.3

This is working correctly.

**Comment by hitiksaini** [comment]
Node.js is successfully installed, and that express thing, you just need to execute the first command, which executed correctly .
Also, you are running commands on home directory, make a folder, perform the steps into a folder.
As fas as installation is concerned, I believe if you got to see your version after --version you've already installed node.js successfully
